version: '3.7'
services:
  mongodb:
    hostname: movie-mongo-db
    container_name: movie-mongo-db-container
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sonal
      MONGO_INITDB_ROOT_PASSWORD: mypassword1!
    volumes:
      - ./data/db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro